trigger:
  - master

stages:
  - stage: "code_quality"
    displayName: "Code Quality Checks"

    jobs:
      - job: "cpp_checks"
        displayName: "C++ Checks"
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - script: |
              sudo apt-get remove -y clang libllvm6.0
              sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
              sudo apt-get update
              sudo apt-get install -y clang-format-6.0
            displayName: 'Install tooling'
          - script: ./.travis/check_clang_format.sh
            displayName: 'Run clang-format'

      - job: "python_checks"
        displayName: "Python Checks"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
          - script: pip install flake8 yapf==0.29.0
            displayName: 'Install tooling'
          - script: ./.travis/check_flake8.sh
            displayName: 'Run flake8'
          - script: yapf --diff --recursive 'python'
            displayName: 'Run yapf'

  - stage: "build_and_test"
    displayName: "Build and Unit Tests"
    jobs:
      - job: "conda_build_and_upload"
        displayName: "Conda Package Builds"
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - script: |
              conda --version
              conda install conda-build
            displayName: "Conda configuration"