trigger:
- master

jobs:
  - job: "code_quality"
    displayName: "Code Quality Checks"

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
      
      - script: |
          sudo apt-get install -y clang-format-6.0
          pip install flake8 yapf==0.29.0
        displayName: 'Install tooling'

      - script: ./.travis/check_clang_format.sh
        displayName: 'Run clang-format'

      - script: ./.travis/check_flake8.sh
        displayName: 'Run flake8'

      - script: yapf --diff --recursive 'python'
        displayName: 'Run yapf'

  - job: "conda_build_and_upload"
    displayName: "Conda Package Builds"

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          conda --version
          conda install conda-build
        displayName: "Conda configuration"