stages:
  - stage: 'code_quality'
    displayName: 'Code Quality Checks'

    jobs:
      - job: 'cpp_checks'
        displayName: 'C++ Checks'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - script: |
              sudo apt-get remove --yes clang libllvm6.0
              sudo add-apt-repository --yes 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
              sudo apt-get update
              sudo apt-get install --yes clang-format-6.0
            displayName: 'Install tooling'
          - script: ./.travis/check_clang_format.sh
            displayName: 'Run clang-format'

      - job: 'cmake_checks'
        displayName: 'CMake Checks'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
          - script: pip install cmake_format==0.6.9
            displayName: 'Install tooling'
          - script: |
              cmake-format --version
              find . -type f -name CMakeLists.txt -or -name '*.cmake' | xargs cmake-format --check
            displayName: 'Run cmake-format'

      - job: 'python_checks'
        displayName: 'Python Checks'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
          - script: pip install flake8 yapf==0.29.0
            displayName: 'Install tooling'
          - script: ./.travis/check_flake8.sh
            displayName: 'Run flake8'
          - script: |
              yapf --version
              yapf --diff --recursive 'python'
            displayName: 'Run yapf'
