name: scipp-docs

channels:
  - conda-forge
  - dannixon

# Note that since the scipp package is installed after this environment is
# created (and Conda is a pain) this list must include the union of the runtime
# and documentation build dependencies.
# See https://scipp.github.io/developer/dependencies.html
dependencies:
  - appdirs
  - ipyevents
  - ipython=7.2.0
  - ipyvolume
  - ipywidgets
  - pandoc
  - python>=3
  - python-configuration
  - pyyaml
  - sphinx>=1.6
  - sphinx_rtd_theme
  - tbb
  - nbsphinx
  - numpy
  - mantid-framework
  - matplotlib
